<a href="https://colab.research.google.com/github/kskrzynska/ds-learning/blob/main/pracadomowa10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Zadanie 1

In [2]:
import numpy as np

In [ ]:
print(f"Wersja Numpy: {np.__version__}")

Wersja Numpy: 2.1.3


In [ ]:
tablica = np.arange(1, 101)

In [ ]:
print("Suma wszystkich elementów:", np.sum(tablica))

Suma wszystkich elementów: 5050


In [ ]:
print("Średnia arytmetyczna:", np.mean(tablica))

Średnia arytmetyczna: 50.5


In [ ]:
print("Mediana:", np.median(tablica))

Mediana: 50.5


In [ ]:
print("Wartość maksymalna:", np.max(tablica))

Wartość maksymalna: 100


In [ ]:
print("Wartość minimalna:", np.min(tablica))

Wartość minimalna: 1


Zadanie 2

In [ ]:
before = np.array([100, 250, 75, 320, 180, 450, 90])

In [ ]:
after = np.array([ 80, 200, 60, 280, 150, 400, 75])

In [ ]:
roznica_miedzy_cenami = before - after

In [ ]:
print(roznica_miedzy_cenami)

[20 50 15 40 30 50 15]


In [ ]:
procent_rabatu = (roznica_miedzy_cenami / before) * 100

In [ ]:
print(procent_rabatu)

[20.         20.         20.         12.5        16.66666667 11.11111111
 16.66666667]


In [ ]:
procent_rabatu = np.round(procent_rabatu, 2)

In [ ]:
print(procent_rabatu)

[20.   20.   20.   12.5  16.67 11.11 16.67]


In [ ]:
srednia_oszczednosc = np.mean(roznica_miedzy_cenami)

In [ ]:
srednia_oszczednosc = np.round(srednia_oszczednosc, 2)

In [ ]:
print(srednia_oszczednosc)

31.43


Zadanie 3

In [ ]:
temps = np.array([15, 18, 22, 25, 23, 20, 17, 14, 16, 19, 21, 24])

In [ ]:
print("Temperatury z dni parzystych:", temps[::2])

Temperatury z dni parzystych: [15 22 23 17 16 21]


In [ ]:
print("Ostatnie pięć temperatur:", temps[-5:])

Ostatnie pięć temperatur: [14 16 19 21 24]


In [ ]:
print("Temperatury w odwrotnej kolejności:", temps[::-1])

Temperatury w odwrotnej kolejności: [24 21 19 16 14 17 20 23 25 22 18 15]


In [ ]:
print("Temperatury większe niż 20:", temps[temps > 20])

Temperatury większe niż 20: [22 25 23 21 24]


Zadanie 4

In [ ]:
np.random.seed(0)

In [ ]:
tablica2d = np.random.randint(1, 51, size=(5, 4))

In [ ]:
print(tablica2d)

[[45 48  1  4]
 [ 4 40 10 20]
 [22 37 24  7]
 [25 25 13  2]
 [39 40 24 47]]


In [ ]:
print("Shape:", tablica2d.shape)

Shape: (5, 4)


In [ ]:
print("Drugi wiersz:", tablica2d[1])

Drugi wiersz: [ 4 40 10 20]


In [ ]:
print("Trzecia kolumna:", tablica2d[:,2])

Trzecia kolumna: [ 1 10 24 13 24]


In [ ]:
print("Element z pozycji [2, 3]:", tablica2d[2, 3])

Element z pozycji [2, 3]: 7


Zadanie 5

In [ ]:
np.random.seed(1)
sales = np.random.randint(10, 100, size=(4, 7))

In [ ]:
print(sales)

[[47 22 82 19 85 15 89]
 [74 26 11 86 81 16 35]
 [60 30 28 94 21 38 39]
 [24 60 78 97 97 96 23]]


In [ ]:
srednia_sprzedaz_produkt = np.mean(sales, axis=1)

In [ ]:
print(srednia_sprzedaz_produkt)

[51.28571429 47.         44.28571429 67.85714286]


In [ ]:
srednia_sprzedaz_dzien = np.mean(sales, axis=0)

In [ ]:
print(srednia_sprzedaz_dzien)

[51.25 34.5  49.75 74.   71.   41.25 46.5 ]


In [ ]:
max_laczna_sprzedaz = np.argmax(sum(sales), axis=0)

In [ ]:
print(max_laczna_sprzedaz)

3


In [ ]:
min_srednia_sprzedaz = np.argmin(srednia_sprzedaz_produkt)

In [ ]:
print(min_srednia_sprzedaz)

2


Zadanie 6

In [ ]:
grades = np.array([78, 45, 92, 67, 34, 88, 56, 91, 23, 85, 73, 95])

In [ ]:
oceny_wysokie = grades[grades >= 80]

In [ ]:
print("Oceny wyoskie:", oceny_wysokie)

Oceny wyoskie: [92 88 91 85 95]


In [ ]:
oceny_ndst = grades[grades < 50]

In [ ]:
print("Oceny niedostateczne:", oceny_ndst)

Oceny niedostateczne: [45 34 23]


In [ ]:
grades_60_80 = np.sum((grades >= 60) & (grades <= 80))

In [ ]:
print("Oceny w przedziale [60, 80):", grades_60_80)

Oceny w przedziale [60, 80): 3


In [ ]:
grades[grades < 50] = 50

In [ ]:
print(grades[grades < 50])

[]


In [ ]:
print(grades)

[78 50 92 67 50 88 56 91 50 85 73 95]


Zadanie 7

In [ ]:
maciez_3x3 = np.zeros((3, 3))

In [ ]:
print(maciez_3x3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
maciez_4x4 = np.ones((4, 4))

In [ ]:
print(maciez_4x4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
maciez_5x5 = np.eye(5)

In [ ]:
print(maciez_5x5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
maciez_3x4 = np.full((3, 4), 7)

In [ ]:
print(maciez_3x4)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
wektor = np.linspace(0, 1, 10)

In [ ]:
print(wektor)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Zadanie 8


In [ ]:
arr = np.arange(1, 13)

In [ ]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr_3x4 = arr.reshape(3, 4)

In [ ]:
print(arr_3x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr_2x6 = arr.reshape(2, 6)

In [ ]:
print(arr_2x6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
arr_4x3 = arr.reshape(4, 3)

In [ ]:
print(arr_4x3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
splaszczone = arr_4x3.flatten()

In [ ]:
print(splaszczone)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
splaszczone2 = arr_4x3.ravel()

In [ ]:
print(splaszczone2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Zadanie 10

In [3]:
exams = np.array([
[78, 85, 92, 88],
[65, 72, 68, 70],
[90, 88, 95, 92],
[55, 60, 58, 62],
[82, 79, 85, 80]
])

In [4]:
bonus = np.array([5, 10, 5, 10])

In [5]:
mnoznik = np.array([1.0, 1.1, 0.95, 1.15, 1.0])

In [7]:
print("Wyniki przed:")
print(exams)

Wyniki przed:
[[78 85 92 88]
 [65 72 68 70]
 [90 88 95 92]
 [55 60 58 62]
 [82 79 85 80]]


In [8]:
z_bonusem = exams + bonus

In [13]:
wyniki = z_bonusem * mnoznik.reshape(5, 1)

In [14]:
print("Wyniki końcowe:")
print(wyniki)

Wyniki końcowe:
[[83.   95.   97.   98.  ]
 [77.   90.2  80.3  88.  ]
 [90.25 93.1  95.   96.9 ]
 [69.   80.5  72.45 82.8 ]
 [87.   89.   90.   90.  ]]


Zadanie 13

In [15]:
np.random.seed(42)
data = np.concatenate([
np.random.randn(100) * 10 + 50,
np.array([150, -50, 200, -100, 180])
])
np.random.shuffle(data)

In [16]:
mean = np.mean(data)

In [17]:
std = np.std(data)

In [18]:
data_standarized = (data - mean) / std

In [19]:
outlier = np.abs(data_standarized) > 3

In [20]:
outliers = data[outlier]

In [21]:
print(outliers)

[ 200.  150.  180.  -50. -100.]


In [22]:
usun_outliers = data[~outlier]

In [23]:
mean2 = np.mean(usun_outliers)

In [24]:
std2 = np.std(usun_outliers)

In [25]:
data_standarized2 = (usun_outliers - mean2) / std2

In [30]:
print("Statystyki przed:")
print(f"mean: {np.mean(data):.2f}")
print(f"std: {np.std(data):.2f}")
print(f"min: {np.min(data):.2f}")
print(f"max: {np.max(data):.2f}")
print(f"liczba elementów: {len(data)}")

Statystyki przed:
mean: 50.25
std: 29.30
min: -100.00
max: 200.00
liczba elementów: 105


In [31]:
print("Statystyki po:")
print("mean:", np.mean(usun_outliers))
print("std:", np.std(usun_outliers))
print("min:", np.min(usun_outliers))
print("max:", np.max(usun_outliers))
print("liczba elementów:", len(usun_outliers))

Statystyki po:
mean: 48.96153482605905
std: 9.036161766446297
min: 23.802548959102555
max: 68.52278184508938
liczba elementów: 100
